### PR TITLE
fix(core-box): stub the renderer URL instead of assigning it

### PR DESCRIPTION
**Pull request by TalexDreamSoul**
**`TalexDreamSoul/app-shell-v2` does not typecheck right now.** Every PR opened against it inherits this.

```
meta-overlay.test.ts(137,12) error TS2704: The operand of a 'delete' operator cannot be a read-only property
meta-overlay.test.ts(139,17) error TS2540: Cannot assign to 'ELECTRON_RENDERER_URL' because it is read-only
meta-overlay.test.ts(144,15) error TS2540: same
```

## How it landed

`electron-vite` declares `ELECTRON_RENDERER_URL` readonly, and every other reader in the tree only *reads* it. #1600 was the first to write one, to give `init()` a URL to resolve.

**The tests pass either way** — which is exactly why it got through: `App suites (core-app)` is `continue-on-error`, so nothing in that PR reported it, and `Typecheck (workspace)` only sees the tree after the merge.

## The fix

`vi.stubEnv` — already the repo's idiom for this (`renderer-override-verification.test.ts`, `screenshot-service.test.ts`). It typechecks, and `vi.unstubAllEnvs` restores the value, which is what the hand-rolled save/restore around the assignment existed for, so that goes too.

Typecheck clean, the six meta-overlay tests pass, eslint clean.

## Note

Not my change and not a criticism of it — #1600 fixed two genuinely broken tests. This is the same class as #1547 earlier today: a PR that is green on its own breaks the base, because the job that would have caught it cannot fail a PR.

### CODE REVIEW

**Comment by TalexDreamSoul** [comment]
更正我在这个 PR 描述里的一句判断。

我写的是「`App suites (core-app)` 是 continue-on-error,所以那个 PR 上没人报告」。**查证后不成立** —— #1600 合并时 `Typecheck (workspace)` 就是 **FAILURE**,闸门准确报了红,是**红着被合并**的。

数了最近 12 个已合并 PR(排除全仓皆红的 `Documentation Quality`):#1600 与 #1602 带着 `PR Quality` + `Typecheck (workspace)` 失败合入,其余 10 个干净。

所以"把 App suites 改成阻塞"这条建议我收回 —— 它解决不了红着合并。详细记在 #959。
