### PR TITLE
fix(plugin): make IFeatureCommand.value the string a manifest can actually carry

### PR DESCRIPTION
**Pull request by TalexDreamSoul**
Fixes the two concrete failures in #885. The larger type-split it proposes is left open — see below.

## The defect

`IFeatureCommand.value` admitted `RegExp` and `FeatureCommandMatcher`, but features are declared in `manifest.json` and cross IPC, where both degrade to a plain string or `{}`. The matcher trusted the type:

| command type | before |
|---|---|
| `regex` | `(command.value as RegExp).test(...)` → **`TypeError: value.test is not a function`** on every real declaration |
| `function` | no branch at all → fell through to `default: return false`, so the feature **silently never matched** |

## The fix

- `value` narrowed to `string | string[]`
- `regex` compiles the pattern at match time, cached per pattern; an invalid pattern is ignored with a warning rather than thrown
- `function` now logs why it cannot work instead of failing silently

## Narrowing a published type is safe here

Nothing used the removed arms:

- `FeatureCommandMatcher` was referenced **only** by its own declaration and that union arm
- no manifest in `plugins/` declares `type: "regex"` or `"function"`
- nothing constructs a `RegExp` value anywhere

`typecheck:node` passes unchanged. The type stays exported and is marked `@deprecated` so existing imports still resolve — an external author passing a `RegExp` was already broken at runtime, so this surfaces an existing bug rather than creating one.

## Verified by mutation

Against the unfixed matcher, **5 of the 6 new cases fail**:

```
unfixed -> 5 failed | 16 passed
fixed   -> 21 passed
```

The sixth asserts `match` / `contain` / `over` are untouched — a careless rewrite of the switch would break it.

## Note on a lint trap hit while doing this

`no-console` is an error in core-app, and my first version used `console.warn`. Worth recording that `npx eslint … | tail` reports the **pipe's** exit code, not eslint's — it printed `exit=0` while eslint was actually exiting 1 with 2 errors. The warnings now go through the file's existing `pluginFeaturesLog`.

## Left open

The issue's suggested direction — splitting a manifest-facing type from a runtime type and compiling `regex` once at manifest load rather than at match time — is a design change beyond removing the crash. Reported on #885.

### CODE REVIEW

**Comment by TalexDreamSoul** [comment]
Left unrebased deliberately — this one needs a decision rather than a mechanical resolution.

`plugin-features-adapter.test.ts` has since been rewritten around a different harness: the base now builds each adapter through `createAdapter()` and attaches a `searchEngineHost` double (`getActivationState` / `activateProviders` / `deactivateProvider`), where this branch still imports `searchEngineCore` directly. Porting the new `isCommandMatch` cases across means re-expressing them against that host double, and I did not want to guess at the intended assertions while doing it.

Everything else in the stale queue has been rebased and re-run. Say the word if you want me to port these cases, or push a rebase yourself and I will verify and merge.

**Comment by TalexDreamSoul** [comment]
## 已解决冲突并 rebase 到最新基线

冲突出在 `plugin-features-adapter.test.ts`,原因是这个 PR 写于 **#523 之前**:基线后来把 adapter 与 search-core 解耦了,而本 PR 仍在 `vi.mock('../../box-tool/search-engine/search-core')`。落后基线 **131 个提交**。

### 两处冲突都是可加性的,不是互斥的

**导入与 setup:** 保留基线的 `attach(searchEngineHost)` 写法,只把本 PR 新增的部分并进去 —— `isCommandMatch` 的导入,以及 `featureLogWarn` 的 logger mock。

**丢弃了**本 PR 里的 `import searchEngineCore` 和对 search-core 的 mock —— 基线现在有一条测试专门断言 adapter **不得** import search-core,把它们留下会让那条测试失败。

**describe 块:** 两个都保留。基线的 `search engine coupling (#523)` 和本 PR 的 `plugin feature command matching` 测的是不同的东西。

### 验证

```
✓ plugin-features-adapter.test.ts (24 tests)
  Tests  24 passed (24)
```

并且确认两边的标志性测试都还在(不是被我合掉了):

- 基线侧:`does not import the search engine`
- 本 PR 侧:`compiles a regex string pattern instead of throwing on it`

`tsc -p tsconfig.node.json` 对该文件无报错;core-app 的 lint-staged 命令退出 0。

现在状态:**MERGEABLE**(此前是 CONFLICTING)。ahead 1 / behind 0。
